// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfoDTO>;

export function DeletePage(arg1:string):Promise<main.SessionDTO>;

export function DownloadUpdate(arg1:string):Promise<main.UpdateDownloadDTO>;

export function ExportSelected(arg1:string):Promise<main.ExportResultDTO>;

export function GetSession():Promise<main.SessionDTO>;

export function ListScanners():Promise<Array<main.ScannerDTO>>;

export function Scan(arg1:main.ScanRequest):Promise<main.ScanResultDTO>;

export function SetPageSelected(arg1:string,arg2:boolean):Promise<main.SessionDTO>;
