// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function ExportSelected(arg1) {
  return window['go']['main']['App']['ExportSelected'](arg1);
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function ListScanners() {
  return window['go']['main']['App']['ListScanners']();
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function SetPageSelected(arg1, arg2) {
  return window['go']['main']['App']['SetPageSelected'](arg1, arg2);
}
