// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeletePage(arg1) {
  return window['go']['main']['App']['DeletePage'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExportSelected(arg1) {
  return window['go']['main']['App']['ExportSelected'](arg1);
}

export function GetArsipinConfig() {
  return window['go']['main']['App']['GetArsipinConfig']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function ListScanners() {
  return window['go']['main']['App']['ListScanners']();
}

export function SaveArsipinConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveArsipinConfig'](arg1, arg2);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function SetPageSelected(arg1, arg2) {
  return window['go']['main']['App']['SetPageSelected'](arg1, arg2);
}

export function UploadSelectedToArsipin() {
  return window['go']['main']['App']['UploadSelectedToArsipin']();
}
